### ISSUE TITLE
Error invalid user/password

### ISSUE THREAD

**Issue by Radiergummi** [rafaelhdr/glewlwyd-oauth2-server#3]
I just tried setting up the image to test Glewlwyd, but the credentials (`admin` and `password`) seem to be wrong. On the other hand, STDERR shows the following:  

```
2018-01-12T14:37:30 - Glewlwyd ERROR: Error executing sql query
2018-01-12T14:37:30 - Glewlwyd ERROR: get_user_database - Error executing j_query
2018-01-12T14:37:30 - Glewlwyd ERROR: get_user - Error getting user
2018-01-12T14:37:30 - Glewlwyd ERROR: callback_glewlwyd_validate_user_session - Error get_user
```

I'm using the `rafaelhdr/glewlwyd-oauth2-server:1.0-sqlite3-quickstart` docker image.

**Comment by rafaelhdr** [comment]
Sorry for closing. It was automatic on merge. Reopening.

**Comment by rafaelhdr** [comment]
@Radiergummi 

I made a bugfix. Could you test, please?

Just change the image (instead 1.0, use 1.1 - `rafaelhdr/glewlwyd-oauth2-server:1.1-sqlite3-quickstart`).

If you want to build by yourself, check the branch [bugfix-invalid-username-password](https://github.com/rafaelhdr/glewlwyd-oauth2-server/tree/bugfix-invalid-username-password).

**Comment by rafaelhdr** [comment]
@Radiergummi 

I think it is fixed in newer versions. If the error continues, please reopen the issue.
