### ISSUE TITLE
How do change webapp front end? 

### ISSUE THREAD

**Issue by cyclonstep** [rafaelhdr/glewlwyd-oauth2-server#8]
Hello, In these past three days I've been wanting to redesign your web app front to based on my needs. I created my own code base using react and not in the default directory. But when i tried to fetch with url =>(e.g : http://localhost:4593/app/auth/user), i found that in my redesigned web app the results that action was 403 forbidden. Why did it end up like this? or  is glewlwyd can only accept request from the directory that have been set up before in glewlwyd.conf ? Your answer is very much appreciated! thank you!

**Comment by rafaelhdr** [comment]
Hi,

You can custom the front-end copying the files to `/usr/share/glewlwyd/webapp/`.

For example, you can copy and edit the [index.htm](https://github.com/babelouest/glewlwyd/blob/master/webapp/index.html)l and use a Dockerfile like below:

```
FROM rafaelhdr/glewlwyd-oauth2-server:quickstart

COPY index.html /usr/share/glewlwyd/webapp/index.html
```

Ok?

**Comment by rafaelhdr** [comment]
Added the customization to README.
